### ISSUE TITLE
How to override outline default behavior?

### ISSUE THREAD

**Issue by ajmalafif** [marina-mosti/tailwindcss-enhanced-outlines-plugin#1]
Hi!

Thank you so much for the plugin! 

I was trying not to have `outline-{color}` in all my pages and instead override the blue outline color, how do I achieve that?

**Comment by marina-mosti** [comment]
Not sure I understand what you're asking. If you want to override globally then you should target * or the body/html

**Comment by ajmalafif** [comment]
Yes that‘s it. I had the impression by adding say `default` on `tailwind.config.js` I can overwrite globally. 

For now overriding globally like you mentioned works!
